spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thermosave
    username: uthermosave
    password: '123thermosave*'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
